# Generated by Django 2.0 on 2019-03-17 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='collected',
            field=models.ManyToManyField(blank=True, related_name='collected_video', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoinfo',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked_video', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoinfo',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='点击量'),
        ),
    ]
