# Generated by Django 2.0 on 2019-03-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20190317_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoinfo',
            old_name='blong',
            new_name='up_man',
        ),
    ]
