# Generated by Django 2.0 on 2019-03-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='up_count',
            field=models.IntegerField(default=0, verbose_name='上传数量'),
        ),
    ]
