# Generated by Django 2.0 on 2019-04-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumscomment',
            old_name='reviewer',
            new_name='user',
        ),
    ]
