# Generated by Django 2.0 on 2019-04-09 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20190408_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumscomment',
            name='forums',
        ),
        migrations.RemoveField(
            model_name='forumscomment',
            name='parent_conment',
        ),
        migrations.RemoveField(
            model_name='forumscomment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='forumsupdown',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='forumsupdown',
            name='forums',
        ),
        migrations.RemoveField(
            model_name='forumsupdown',
            name='user',
        ),
        migrations.RenameField(
            model_name='forums',
            old_name='comment_count',
            new_name='view_count',
        ),
        migrations.DeleteModel(
            name='ForumsComment',
        ),
        migrations.DeleteModel(
            name='ForumsUpDown',
        ),
    ]
